service: nestjs-typescript-challenge

frameworkVersion: "4"

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  ecr:
    images:
      myimage: # Nombre de imagen en minúsculas
        uri: 544022947556.dkr.ecr.us-east-1.amazonaws.com/test-ecr-2:latest
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  stage: dev
  region: us-east-1
  environment: 
    PORT: ${env:PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_DATABASE: ${env:DB_DATABASE}

functions:
  main:
    image:
      name: myimage # Nombre de imagen en minúsculas
    events:
      - http:
          method: ANY
          path: /{proxy+}

custom:
  optimize:
    external: ['swagger-ui-dist']
  serverless:
    licenseKey: ${env:SERVERLESS_LICENSE_KEY}
